feat: Refactor cognito infra (#30)
* chore: refactor application files into src folder

* chore: update workflows

* chore: update workflows

* trigger

* trigger

* trigger

* test

* chore: clean workflows

* use # type: ignore

* chore: version bump

* trigger image build based on pyprokect.toml

* ls

* trigger

* update main workflow

* rebuild

* feat: move infra folder to this repository from datalake

* chore: update workflows

* chore: modify .gitignore

* chore: add package.lock

* chore: add tsconfig.base.json

* chore: add oidc auth

* chore: update changelog & relax reusable-get-files-with-changes.yaml

* chore: add whitespace

* feat: add .dockerignore

* feat: point to actual Dockerfile

* set image from workflow instead of from cdk; todo: deprecate cdk.context.json value

* set img version in pipeline

* chore: update workflows version logic

* chore: handle versioning

* chore: cover warning w.r.t. ::set-output

* chore: use env vars

* chore: test

* debugging

* debuggin variable passing

* test

* debugging

* test

* test

* test

* feat: use dynamic tags

* refactor workflows

* chore: refactor and clean workflows

* chore: debug workflows since the non refacotred one works

* test

* missing inherit secrets

* add secrets in feature workflow

* version determination

* secrets

* chore: add secret to all jobs on main

* chore: trigger build after updating sonar and repo configs

* chore: fix sonar issues

* chore: update entrypoint main

* chore: update readme and move docs folder

* chore: explicit job output seem to be needed

* Updated Pipeline

---------

Co-authored-by: Akash Gupta <akash.gupta@postnl.nl>

diff --git a/.github/workflows/entrypoint-main.yaml b/.github/workflows/entrypoint-main.yaml
--- a/.github/workflows/entrypoint-main.yaml
+++ b/.github/workflows/entrypoint-main.yaml
@@ -6,46 +6,63 @@ on:
     branches: [main]
 
 jobs:
-  get-files-with-changes:
-    name: Get Files with changes
-    uses: ./.github/workflows/reusable-get-files-with-changes.yaml
-    
-  deploy-docker-image-to-tst:
-    name: Deploy Docker Image to Test
-    needs: [get-files-with-changes]
-    if: needs.get-files-with-changes.outputs.changed-files != '[]' &&
-      !failure() &&
-      !cancelled()
-    uses: ./.github/workflows/reusable-build-deploy-docker-image.yaml
+  get-application-version:
+    name: Fetching version of application
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.set-application-version.outputs.tag }}
+    steps:
+      - name: Checkout branch
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Get Application Versions from pyproject.toml
+        id: set-application-version
+        run: |
+          if [ ! -f "src/pyproject.toml" ]; then
+            echo "::error ::src/pyproject.toml file not found in the current branch"
+            exit 1
+          fi
+          application_version=$(grep "^version" src/pyproject.toml | head -n 1 | cut -d '"' -f 2)
+          if [ -n "$application_version" ]; then
+            echo "Using current version: $application_version"
+            echo "tag=$(echo $application_version)" >> $GITHUB_OUTPUT
+          else
+            echo "::error ::application-version not provided or is empty"
+            exit 1
+          fi
+
+
+  deploy-infra-to-tst:
+    name: Deploy Cognito Infrastructure to Test
+    needs: get-application-version
+    if: needs.get-application-version.outputs.version != '[]' && !failure() && !cancelled()
+    uses: ./.github/workflows/reusable-deploy-infra.yaml
     with:
       environment: test
       stage: tst
+      application-version: ${{ needs.get-application-version.outputs.version }}
     secrets: inherit
 
-
-  deploy-docker-image-to-acc:
-    name: Deploy Docker Image to Acceptance
-    needs: [get-files-with-changes, deploy-docker-image-to-tst]
-    if: needs.get-files-with-changes.outputs.changed-files != '[]' &&
-      !failure() &&
-      !cancelled()
-    uses: ./.github/workflows/reusable-build-deploy-docker-image.yaml
+  deploy-infra-to-acc:
+    name: Deploy Cognito Infrastructure to Acceptance
+    needs: [get-application-version, deploy-infra-to-tst]
+    if: needs.get-application-version.outputs.version != '[]' && !failure() && !cancelled()
+    uses: ./.github/workflows/reusable-deploy-infra.yaml
     with:
       environment: acceptance
       stage: acc
+      application-version: ${{ needs.get-application-version.outputs.version }}
     secrets: inherit
 
-
-  deploy-docker-image-to-prd:
-    name: Deploy Docker Image to Production
-    needs: [get-files-with-changes, deploy-docker-image-to-acc]
-    if: needs.get-files-with-changes.outputs.changed-files != '[]' &&
-      !failure() &&
-      !cancelled()
-    uses: ./.github/workflows/reusable-build-deploy-docker-image.yaml
+  deploy-infra-to-prd:
+    name: Deploy Cognito Infrastructure to Production
+    needs: [get-application-version, deploy-infra-to-acc]
+    if: needs.get-application-version.outputs.version != '[]' && !failure() && !cancelled()
+    uses: ./.github/workflows/reusable-deploy-infra.yaml
     with:
       environment: production
       stage: prd
+      application-version: ${{ needs.get-application-version.outputs.version }}
     secrets: inherit
-
-    
diff --git a/.github/workflows/reusable-check-package-version-bumping.yaml b/.github/workflows/reusable-check-package-version-bumping.yaml
--- a/.github/workflows/reusable-check-package-version-bumping.yaml
+++ b/.github/workflows/reusable-check-package-version-bumping.yaml
@@ -1,46 +1,70 @@
-# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
+# reusable-check-package-version-bumping.yaml
 name: Check if a package version is bumped
 
 on:
-  workflow_call
+  workflow_call:
+    inputs:
+      working-directory:
+        description: 'Directory where the application is located'
+        required: false
+        default: '.'
+        type: string
+    outputs:
+      current-version:
+        description: "Current version of the package"
+        value: ${{ jobs.check-version.outputs.current-version }}
 
 jobs:
   check-version:
     runs-on: ubuntu-latest
+    outputs:
+      current-version: ${{ steps.compare_versions.outputs.current-version }}
     steps:
       - name: Checkout current branch
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.head_ref }}
+          fetch-depth: 0
 
       - name: Checkout main branch
         uses: actions/checkout@v4
         with:
           ref: main
-          path: main_branch
+          path: main_branch 
 
       - name: Compare and set versions
         id: compare_versions
         run: |
-          # Extract version from current branch
-          current_version=$(grep "^version" pyproject.toml | head -n 1 | cut -d '"' -f 2)
-          
-          # Extract version from main branch
-          main_version=$(grep "^version" main_branch/pyproject.toml | head -n 1 | cut -d '"' -f 2)
+          if [ ! -f "src/pyproject.toml" ]; then
+            echo "::error ::src/pyproject.toml file not found in the current branch"
+            exit 1
+          fi
+
+          if [ ! -f "main_branch/src/pyproject.toml" ]; then
+            if [ -f "main_branch/pyproject.toml" ]; then
+              main_version=$(grep "^version" main_branch/pyproject.toml | head -n 1 | cut -d '"' -f 2)
+            else
+              echo "::error ::Neither src/pyproject.toml nor root-level pyproject.toml found in main branch"
+              exit 1
+            fi
+          else
+            main_version=$(grep "^version" main_branch/src/pyproject.toml | head -n 1 | cut -d '"' -f 2)
+          fi
+
+          current_version=$(grep "^version" src/pyproject.toml | head -n 1 | cut -d '"' -f 2)
 
           echo "Current branch version: $current_version"
           echo "Main branch version: $main_version"
 
-          if [ "$current_version" = "$main_version" ];
-          then
-              echo "::error ::Version $current_version is equal to $main_version"
-              exit 1
-          elif [ "$current_version" \< "$main_version" ];
-              then
-                  echo "::error ::Version $current_version is less than $main_version"
-                  exit 1
+          # Set the job outputs
+          echo "current-version=$current_version" >> $GITHUB_OUTPUT
+          echo "main-version=$main_version" >> $GITHUB_OUTPUT
+
+          if [ "$current_version" = "$main_version" ]; then
+            echo "::error ::Version $current_version is equal to $main_version"
+            exit 1
+          elif [ "$current_version" \< "$main_version" ]; then
+            echo "::error ::Version $current_version is less than $main_version"
+            exit 1
           else
-              echo "::notice ::Version $current_version is greater than $main_version"
-              exit 0
+            echo "::notice ::Version $current_version is greater than $main_version"
           fi
-          
