trigger

diff --git a/.github/workflows/reusable-check-package-version-bumping.yaml b/.github/workflows/reusable-check-package-version-bumping.yaml
--- a/.github/workflows/reusable-check-package-version-bumping.yaml
+++ b/.github/workflows/reusable-check-package-version-bumping.yaml
@@ -1,4 +1,3 @@
-# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 name: Check if a package version is bumped
 
 on:
@@ -8,6 +7,7 @@ on:
         description: 'Directory where the application is located'
         required: false
         default: '.'
+        type: string  # Add the type field
 
 jobs:
   check-version:
@@ -17,7 +17,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.head_ref }}
-          path: ${{ inputs.working-directory }}  # Checkout into the correct directory
+          path: ${{ inputs.working-directory }}
 
       - name: Checkout main branch
         uses: actions/checkout@v4
@@ -28,23 +28,18 @@ jobs:
       - name: Compare and set versions
         id: compare_versions
         run: |
-          # Extract version from current branch
           current_version=$(grep "^version" ${{ inputs.working-directory }}/pyproject.toml | head -n 1 | cut -d '"' -f 2)
-          
-          # Extract version from main branch
           main_version=$(grep "^version" main_branch/${{ inputs.working-directory }}/pyproject.toml | head -n 1 | cut -d '"' -f 2)
 
           echo "Current branch version: $current_version"
           echo "Main branch version: $main_version"
 
-          if [ "$current_version" = "$main_version" ];
-          then
+          if [ "$current_version" = "$main_version" ]; then
               echo "::error ::Version $current_version is equal to $main_version"
               exit 1
-          elif [ "$current_version" \< "$main_version" ];
-              then
-                  echo "::error ::Version $current_version is less than $main_version"
-                  exit 1
+          elif [ "$current_version" \< "$main_version" ]; then
+              echo "::error ::Version $current_version is less than $main_version"
+              exit 1
           else
               echo "::notice ::Version $current_version is greater than $main_version"
               exit 0
